name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        composer-flags: ['', '--prefer-lowest --prefer-stable']
    name: PHP ${{ matrix.php-versions }} tests | ${{ matrix.composer-flags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Cache/Restore dependencies
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-${{ matrix.php-version }}
          restore-keys: php-${{ matrix.php-version }}

      - name: Install Dependencies
        run: composer update ${{ matrix.composer-flags }} --no-interaction --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit

  code-coverage:
    runs-on: ubuntu-latest
    name: Collecting code-coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug

      - name: Cache/Restore dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-8.1
          restore-keys: php-8.1

      - name: Install Dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v  --json_path coveralls.json

  coding-standard:
    runs-on: ubuntu-latest
    name: Checking coding standard
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Cache/Restore dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-8.1
          restore-keys: php-8.1

      - name: Install Dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Check coding standard
        run: composer cs

  phpstan:
    runs-on: ubuntu-latest
    name: Performing static analysis (PHPStan)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Cache/Restore dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-8.1
          restore-keys: php-8.1

      - name: Install Dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPStan
        run: composer stan
